use serde::{Deserialize, Serialize};

use crate::engine::capabilities::podman::labels::sanitize_file_stem;

pub const MANAGED_HEADER: &str = "# Generated by cadman. Do not edit.";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CaddySiteRoute {
    pub id: String,
    pub hosts: Vec<String>,
    pub path: Option<String>,
    pub upstream: String,
}

pub fn site_file_name(id: &str) -> String {
    format!("{}.site", sanitize_file_stem(id))
}

pub fn site_content(route: &CaddySiteRoute) -> String {
    let hosts = route.hosts.join(" ");
    let matcher = route
        .path
        .as_deref()
        .filter(|path| !path.trim().is_empty())
        .map(|path| format!(" {}*", path.trim()))
        .unwrap_or_default();

    format!(
        "{MANAGED_HEADER}\n{hosts} {{\n    reverse_proxy{matcher} {}\n}}\n",
        route.upstream
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn route(hosts: Vec<&str>, path: Option<&str>) -> CaddySiteRoute {
        CaddySiteRoute {
            id: "app".to_string(),
            hosts: hosts.into_iter().map(str::to_string).collect(),
            path: path.map(str::to_string),
            upstream: "app:8080".to_string(),
        }
    }

    #[test]
    fn site_file_name_is_sanitized() {
        assert_eq!(site_file_name("../app:8080"), "app-8080.site");
    }

    #[test]
    fn single_host_site_content() {
        let content = site_content(&route(vec!["app.local"], None));

        assert!(content.contains("app.local {"));
        assert!(content.contains("reverse_proxy app:8080"));
    }

    #[test]
    fn multi_host_site_content() {
        let content = site_content(&route(vec!["one.local", "two.local"], None));

        assert!(content.contains("one.local two.local {"));
    }

    #[test]
    fn path_matcher_content() {
        let content = site_content(&route(vec!["app.local"], Some("/api")));

        assert!(content.contains("reverse_proxy /api* app:8080"));
    }

    #[test]
    fn generated_header_exists() {
        assert!(
            site_content(&route(vec!["app.local"], None))
                .starts_with("# Generated by cadman. Do not edit.")
        );
    }
}
