[package]
name = "cadman"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
tokio = { version = "1.35", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

scriba = { version = "0.5", features = ["full"] }
veltrix = { path = "../../veltrix/workspace/veltrix", features = ["full"] }
thiserror = "1"
toml = "0.8"
termsize = "0.1"
serde_yaml = "0.9"

[[bin]]
name = "cadman"
path = "src/main.rs"
